@url = http://localhost:3000

###POST
POST {{url}}/users
Content-Type: application/json

{
    "name":"matheus",
    "password":"Teste123*"
}

###GET
GET {{url}}/users

###DELETE
DELETE {{url}}/users/matheus

###PUT
PATCH {{url}}/users/matheus
Content-Type: application/json

{
    "password":"1991"
}

###POST
POST {{url}}/login
Content-Type: application/json

{
    "name":"matheus",
    "password":"Teste123*"
}